version: "2"

services:
  slsdk:
    build: ./slsdk
    restart: always
    privileged: true
    ports:
      - 5030:5030
      - 5031:5031
      - 50300:50300
      # TODO: add volume for music if needed