version: '2'
volumes:
  minio:
services:
  slskd:
    build: ./slskd
    restart: always
    privileged: true
    ports:
      - 5030:5030
      - 5031:5031
      - 50300:50300
    environment:
      SLSK_USR:
      SLSK_PWD:
      # TODO: add volume for music if needed
  minio:
    build: ./minio
    ports:
     - 9000:9000
     - 9090:9090
     - 9001:9001
    volumes:
      - 'minio:/data'
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password
