version: '2'
services:
  slskd:
    build: ./slskd
    restart: always
    privileged: true
    ports:
      - 5030:5030
      - 5031:5031
      - 50300:50300
    environment:
      SLSK_USR:
      SLSK_PWD:
      # TODO: add volume for music if needed
