FROM balenalib/armv7hf-alpine:3.15
RUN install_packages wget && \
  wget https://dl.min.io/server/minio/release/linux-arm64/minio && \
  chmod +x minio && \
  mkdir minio-binaries && \
  wget https://dl.min.io/client/mc/release/linux-arm64/mc -O minio-binaries/mc && \
  chmod +x /minio-binaries/mc
ENV PATH="${PATH}:/minio-binaries/"
ENTRYPOINT ["./minio", "server", "/mnt/data", "--console-address", ":9001"]