FROM balenalib/armv7hf-alpine:3.15
RUN install_packages wget && \
  wget https://dl.min.io/server/minio/release/linux-arm64/minio && \
  chmod +x minio
ENTRYPOINT ["./minio", "server", "/mnt/data", "--console-address", ":9001"]